daily_fresh/daily_fresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/',include('user.urls',namespace='user')),#user
    url(r'^tinymce/', include('tinymce.urls')),#tinymce

    url(r'^goods/',include('goods.urls',namespace='goods')),#user
]

daily_fresh/user/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from user import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^index$', views.index,name='index'),
    url(r'^register$', views.RedisterView.as_view(),name='register'),#注册
    url(r'^user_name_exist$', views.user_name_exist,name='user_name_exist'),#异步判断用户名是否存在

    url(r'^active/(?P<token>.*)$', views.ActiveView.as_view(),name='active'),#账户激活

    url(r'^login$', views.LoginView.as_view(),name='login'),#登录
    url(r'^validate_code$', views.validate_code, name='validate_code'),#验证码

    url(r'^logout_view$', views.logout_view, name='logout_view'),  # 注销/退出

    url(r'^userinfo$', views.UserInfoView.as_view(),name='userinfo'),#用户中心——信息页
    url(r'^order$', views.UserOrderView.as_view(),name='order'),#用户中心——订单页
    url(r'^address$', views.UserAddressView.as_view(),name='address'),#用户中心——地址页

    # url(r'^$', login_required(views.UserInfoView.as_view()),name='userinfo'),#用户中心——信息页
    # url(r'^order$', login_required(views.UserOrderView.as_view()),name='order'),#用户中心——订单页
    # url(r'^address$', login_required(views.UserAddressView.as_view()),name='address$'),#用户中心——地址页



    url(r'^forget_pwd$', views.forget_pwd,name='forget_pwd'),#忘记密码
    url(r'^success_send$', views.success_send,name='success_send'),#成功发送邮件
    url(r'^pwd_reset/(?P<token>.*)$', views.pwd_reset,name='pwd_reset'),#重置密码
    url(r'^pwd_reset_handler$', views.pwd_reset_handle,name='pwd_reset_handle'),#重置密码


    url(r'^get_all_province$', views.get_all_province, name='get_all_province'),#三级联动
    url(r'^get_city_by_pid$', views.get_city_by_pid, name='get_city_by_pid'),
    url(r'^get_area_by_cid$', views.get_area_by_cid, name='get_area_by_cid'),



]

daily_fresh/user/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from db.base_model import BaseModel


class User(AbstractUser,BaseModel):

    # 用户模型类
    class Meta:
        db_table = 'userinfo'
        verbose_name='用户'
        verbose_name_plural=verbose_name

class Province(models.Model):
    pname = models.CharField(max_length=100)
    def __str__(self):
        return self.pname


class City(models.Model):
    cname = models.CharField(max_length=100)
    cprovince=models.ForeignKey(Province)
    def __str__(self):
        return self.cname

class Area(models.Model):
    aname = models.CharField(max_length=100)
    acity=models.ForeignKey(City)
    def __str__(self):
        return self.aname

class Address(BaseModel): # BaseModel 自己写的utils.models下，继承了记录时间字段
    """
    用户的收货地址
    """
    # 关联等级：CASCADE　表示主键被删除了，则外键对应的数据也被删除，级联删除
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='addresses', verbose_name='用户')
    receiver = models.CharField(max_length=20, verbose_name='收货人')
    # 关联等级：PROTECT 表示主键删除的时候，必须外键先被删除，保护
    province = models.ForeignKey('Province', on_delete=models.PROTECT, related_name='province_addresses', verbose_name='省')
    city = models.ForeignKey('City', on_delete=models.PROTECT, related_name='city_addresses', verbose_name='市')
    district = models.ForeignKey('Area', on_delete=models.PROTECT, related_name='district_addresses', verbose_name='区')
    place = models.CharField(max_length=50, verbose_name='地址')
    mobile = models.CharField(max_length=11, verbose_name='手机')
    postcode=models.CharField(max_length=6,verbose_name='邮政编码')
    is_default=models.BooleanField(default=False,verbose_name='是否设为默认')

    class Meta:
        db_table = 'address'
        verbose_name = '用户地址'
        verbose_name_plural = verbose_name

daily_fresh/user/views.py
from django.shortcuts import render,redirect
from django.conf import settings
from  user.models import *
from utils import my_md5
from django.http import HttpResponse,JsonResponse
import json
import re
from django.core.urlresolvers import reverse
# 引入绘图模块
from PIL import Image,ImageDraw,ImageFont
import random
from io import BytesIO
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer,SignatureExpired,BadSignature
from daily_fresh import settings
from django.views.generic import View
from django.core.mail import send_mail
from django.contrib.auth import authenticate,login,logout
from my_celery.celery_tasks import tasks_send_mail
from utils.user_utils import LoginRequiredMixin
from django.core import serializers




def index(request):
    user_name = request.session.get('user_name')
    context = {
               'user_name': user_name,
               }
    return render(request,'user/index.html',context)

class RedisterView(View):
    def get(self,request):
        # 注册页面
        return render(request, 'user/register.html')

    def post(self,request):
        '''注册处理'''
        # 获取属性
        user_name = request.POST.get('user_name', '').strip()
        pwd = request.POST.get('pwd', '').strip()
        cpwd = request.POST.get('cpwd', '').strip()
        email = request.POST.get('email', '').strip()
        allow = request.POST.get('allow')

        # 判断数据完整性
        if not all([user_name, pwd, email, cpwd, allow]):
            return render(request, 'user/register.html', {'errors': '请完善您的信息！'})

        # 校验两次输入的密码是否相同
        if cpwd != pwd:
            return render(request, 'user/register.html', {'errors': '密码输入不一致！！'})

        # 检验邮箱
        if not re.match('^[.a-zA-Z0-9_-]\w{4,20}@(163|qq|126)\.com$', email):
            return render(request, 'user/register.html', {'errors': '邮箱格式不正确！'})

        # 校验用户名是否重复
        if User.objects.filter(username=user_name):
            return render(request, 'user/register.html', {'errors': '用户名重复！'})

        if user_name == '':
            return render(request, 'user/register.html', {'errors': '用户名不能为空！'})

        # try:
        #     user=User.objects.get(username=user_name)
        # except user.DoesNotExist:
        #     # 用户名不存在
        #     user=None
        # if user:
        #     return render(request, 'user/register', {'errors': '用户名重复！'})

        # 进行用户注册
        user = User.objects.create_user(user_name, email, pwd)
        user.is_active = 0
        user.save()

        '''
        发送邮件激活，包含激活链接：http://ip:port/user/cctive/3
        激活链接中需要包含用户的身份信息，并且要把身份信息进行加密
        '''

        # 加密用户的身份信息，生成激活token
        serializer = Serializer(settings.SECRET_KEY, 3600)
        info = {'confirm': user.id}
        token = serializer.dumps(info).decode()
        encryption_url = 'http://192.168.12.202:2222/user/active/%s' % token

        # 发邮件
        subject = '天天生鲜欢迎信息'  # 主题
        message = ''  # 文本内容
        sender = settings.EMAIL_FROM  # 发件人
        receiver = [email]  # 收件人
        html_message = '<h1>%s,欢迎您成为天天生鲜的注册会员</h1>请点击下面的链接激活您的账户</br><a href="%s">%s</a>' % (
        user_name, encryption_url, encryption_url)

        # 发送邮件
        tasks_send_mail.delay(subject, message, sender, receiver, html_message)

        # 返回应答，跳转到登录界面
        return render(request, 'user/login.html')

 #异步处理：判断注册时用户户名是否存在
def user_name_exist(request):
    user_name = request.GET.get('user_name')
    count = User.objects.filter(username=user_name).count()  # [{'name': 'mouhuan'}]
    return JsonResponse({'count':count})


class ActiveView(View):
    '''用户激活'''
    def get(self,request,token):
        '''进行用户激活'''
        #进行解密，获取要激活的用户信息
        serializer=Serializer(settings.SECRET_KEY,3600)
        try:
            info=serializer.loads(token)
            #获取待激活用户的id
            user_id=info['confirm']

            #根据id获取用户信息
            user=User.objects.get(id=user_id)
            user.is_active=1
            user.save()

            #跳转到登陆界面
            return render(request, 'user/login.html')

        except SignatureExpired as e:
            #激活链接已过期
            return HttpResponse('激活链接已过期！')
        except BadSignature as e:
            #激活链接被修改
            return HttpResponse('激活链接非法！')



class LoginView(View):
    '''登录'''

    def get(self,request):
        '''显示登录界面'''

        #判断是否选择了记住用户名
        remeber_user_name = request.COOKIES.get('remeber_user_name', '')
        if remeber_user_name:
            return render(request, 'user/login.html', {'remeber_user_name': remeber_user_name})
        else:
            return render(request, 'user/login.html')

    def post(self,request):
        '''登录校验'''
        #接收数据
        user_name = request.POST.get('username')
        pwd = request.POST.get('pwd')
        validate = request.POST.get('validate')
        remember = request.POST.get('remember')

        user = authenticate(username=user_name, password=pwd)
        # 用户存在
        if user is not None:

            # 判断验证码是否正确
            if validate == request.session.get('validate_code').lower():

                # 验证是否激活
                if user.is_active:
                    #记录用户的登录状态
                    login(request, user)

                    #获取url后面的参数（next=xxxx），记录用户登录前访问的页面，登陆后跳转到访问页面
                    #虽然是post请求，但是要用get方法获取，因为是rl后面携带的参数
                    next_url=request.GET.get('next')
                    print(next_url)
                    if next_url:
                        resp= redirect(next_url)
                    else:
                        resp = redirect(reverse('user:index'))

                    #判断是否记住用户名
                    if remember != None:
                        resp.set_cookie('remeber_user_name', user_name, 3600 * 24 * 7)
                    else:
                        resp.set_cookie('remeber_user_name', user_name, 0)

                    # 将用户id和用户名保存在session中
                    # request.session['user_id'] = user[0].id
                    request.session['user_name']=user_name


                    return resp
                else:
                    # 用户未激活
                    return render(request, 'user/login.html', {'doNotActive': '您的账号还没有激活，请注意查收邮箱消息，进行激活'})
            else:
                return render(request, 'user/login.html', {'validate_error': '验证码错误'})

        else:
            # 用户不存在
            return render(request, 'user/login.html', {'doNotUser': '用户名或密码错误'})

def logout_view(request):
    # 退出登录，清除session
    logout(request)
    request.session.flush()
    return redirect(reverse('user:index'))



class UserInfoView(LoginRequiredMixin,View):
    '''用户中心——信息页'''

    def get(self,request):
        # 获取登录用户对应的user对象
        user = request.user

        # 获取用户的默认收货地址
        try:
            address = Address.objects.get(user=user, is_default=True)
        except Address.DoesNotExist:
            # 不存在默认收货地址
            address = None

        #从session中获取用户名
        user_name=request.session.get('user_name')
        context={'page':'1',
                 'user_name':user_name,
                 'address':address
                 }

        return render(request,'user/user_center_info.html',context)



class UserOrderView(LoginRequiredMixin,View):
    '''用户中心——订单页'''

    def get(self, request):
        user_name = request.session.get('user_name')
        context = {'page': '2',
                   'user_name': user_name
                   }
        return render(request, 'user/user_center_order.html', context)

def get_all_province(request):
    province_list=Province.objects.all()
    content={
        'province_list':serializers.serialize('json',province_list),
    }
    return JsonResponse(content)

def get_city_by_pid(request):
    province_id=request.GET.get('province_id')
    print(province_id)

    province=Province.objects.get(id=province_id)
    print(province)

    city_list=City.objects.filter(cprovince_id=province_id)
    content={
        'city_list':serializers.serialize('json',city_list)
    }
    return JsonResponse(content)

def get_area_by_cid(request):
    city_id=request.GET.get('city_id')

    city=City.objects.get(id=city_id)
    print(city)

    area_id = request.GET.get("area_id")
    print(area_id)

    area_list=Area.objects.filter(acity_id=city_id)
    print(area_list)

    content={
        'area_list':serializers.serialize('json',area_list)
    }
    return JsonResponse(content)

class UserAddressView(LoginRequiredMixin,View):
    '''用户中心——地址页'''

    def get(self, request):
        #获取登录用户对应的user对象
        user=request.user

        #获取用户的默认收货地址
        try:
            address=Address.objects.get(user=user,is_default=True)
        except Address.DoesNotExist:
            #不存在默认收货地址
            address=None
        #数据字典
        user_name = request.session.get('user_name')
        all_address=request.session.get('all_address')
        context = {'page': '3',
                   'user_name': user_name,
                   'address':address,
                   'all_address':all_address
                   }
        return render(request, 'user/user_center_site.html', context)

    def post(self,request):
        '''地址的添加'''

        #接收数据
        receiver=request.POST.get('receiver')
        place=request.POST.get('place')
        postcode=request.POST.get('postcode')
        mobile=request.POST.get('mobile')

        province_id = request.POST.get('province_id')
        try:
            province = Province.objects.get(id=province_id)
        except:
            province=None
        print(province)

        city_id = request.POST.get('city_id')
        try:
            city = City.objects.get(id=city_id)
        except:
            city=None
        print(city)

        area_id = request.POST.get('area_id')
        try:
            area = Area.objects.get(id=area_id)
        except:
            area=None
        print(area)

        # 数据字典
        user_name = request.session.get('user_name')
        # 获取登录用户对应的user对象
        user = request.user

daily_fresh/templates/user/base.html
<!-- 首页 注册 登录-->
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}

<head>
    <meta charset="UTF-8">
    <!--网页标题内容块-->
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">

    <!--网页顶部引入文件块-->
    {% block topfiles %}{% endblock topfiles %}

</head>
<body>
<!--网页顶部欢迎信息块-->
{% block header_con %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
{#				<div class="login_info fl">#}
{#					欢迎您：<em>张 山</em>#}
{#				</div>#}

                {% if user_name %}
                    <div class="login_info fl">
                       欢迎您：<em>{{ user_name }}</em>
                    <span>|</span>
                    <a href="{% url 'user:logout_view' %}" >注销</a>
                    </div>

                {% else %}

				<div class="login_btn fl">
					<a href="login">登录</a>
					<span>|</span>
					<a href="register">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="userinfo">用户中心</a>
					<span>|</span>
					<a href="cart">我的购物车</a>
					<span>|</span>
					<a href="order">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header_con %}


<!--网页顶部搜索框块-->
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>
{% endblock search_bar %}

<!--网页主题内容块-->
{% block body %}{% endblock body %}


<!--网页底部内容-->
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

<!--网页底部html元素块-->
{% block bottom %}{% endblock bottom %}


<!--网页底部引入文件块-->
{% block bottomfiles %}{% endblock bottomfiles %}


</body>
</html>

daily_fresh/templates/user/base_detail_list.html
<!--详情页   列表页-->
{% extends 'user/base.html' %}

<!--网页主题内容块-->
{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

<!--详情页  列表页主题内容块-->
{% block main_content %}{% endblock main_content %}

{% endblock body %}

daily_fresh/templates/user/base_no_cart.html
<!--购物车   提交订单-->
{% extends 'user/base.html' %}

{% load staticfiles %}

<!--网页顶部搜索框-->
{% block search_bar %}
    <div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock search_bar %}

daily_fresh/templates/user/cart.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-购物车</title>
	<link rel="stylesheet" type="text/css" href="css/reset.css">
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="login.html">登录</a>
					<span>|</span>
					<a href="register.html">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="total_count">全部商品<em>2</em>件</div>	
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="images/goods/goods012.jpg"></li>
		<li class="col03">奇异果<br><em>25.80元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">25.80元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="1">	
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">25.80元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>

	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src="images/goods/goods003.jpg"></li>
		<li class="col03">大兴大棚草莓<br><em>16.80元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">16.80元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="1">	
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">16.80元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
	

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>2</b>件商品</li>
		<li class="col04"><a href="place_order.html">去结算</a></li>
	</ul>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

daily_fresh/templates/user/forget.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>忘记密码</title>

<style>
.out{
    width: 900px;
    height: 900px;
    margin: 0 auto;
    margin-top: 100px;
}
</style>
</head>
<body>


    <div class="out">
        <h1>真粗心，忘了密码吗？快通过邮箱找回密码吧！</h1>
        <form method="post" action="/user/success_send">
        {% csrf_token %}
            <P><span>用户名：</span><input type="text" name="user_name"></P>
            <P><span>邮&nbsp;&nbsp;&nbsp;箱：</span><input type="text" name="email"></P>
            <p><input type="submit" value="确认发送验证邮件"></p>
        </form>
        <h1>{{ errors }}</h1>
    </div>


</body>
</html>

daily_fresh/templates/user/pwd_reset.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>重置密码</title>

<style>
.out{
    width: 600px;
    height: 900px;
    margin: 0 auto;
    margin-top: 100px;
}
</style>
</head>
<body>


    <div class="out">

        <h1>可以重新设置一个好记的新密码啦！</h1>
        <form method="post" action="{% url 'user:pwd_reset_handle' %}">
        {% csrf_token %}
            <P><span>新&nbsp;&nbsp;&nbsp;密&nbsp;&nbsp;&nbsp;码：</span><input type="password" name="newpwd1" placeholder="至少8位"></P>
            <P><span>确认新密码：</span><input type="password" name="newpwd2" placeholder="至少8位"></P>

            <input type="hidden" name="email" value="{{ email }}">
            <input type="hidden" name="path" value="{{ path }}">
            <p><input type="submit" value="确认"></p>
        </form>
        <h1>{{ errors }}</h1>

    </div>


</body>
</html>

daily_fresh/templates/user/user_center_site.html

{% extends 'user/base_user_center.html' %}
{% block topfiles %}
    {% load static from staticfiles %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            //发送请求省份，显示所有省份
            get_all_province()
            //为省绑定事件
            change_province()
            //为市绑定事件.
            change_city()
        })

        function get_all_province() {
             $.ajax({
                url:'{% url 'user:get_all_province' %}',
                success:function (data) {
                    province_list=eval('('+data.province_list+')')
                    $.each(province_list,function (index,item) {
                        var option='<option value="'+item.pk+'">'+item.fields.pname+'</option>'
                        $('#province_id').append(option)
                    })
                }
            })
        }

        function change_province() {
            $('#province_id').change(function () {
                province_id=$('#province_id').val()
                $('#city_id').html('<option value="0">-------</option>')
                $('#area_id').html('<option value="0">-------</option>')
                if(province_id!=0){
                    $.ajax({
                        url:'/user/get_city_by_pid',
                        data:{
                            'province_id':province_id
                        },
                        success:function (data) {
                        city_list=eval('('+data.city_list+')')
                        $.each(city_list,function (index,item) {
                            var option='<option value="'+item.pk+'">'+item.fields.cname+'</option>'
                            $('#city_id').append(option)
                            })
                        },
                    })

                }
            })
        }

        function change_city() {
            $('#city_id').change(function () {
                city_id=$('#city_id').val()
                $('#area_id').html('<option value="0">-------</option>')
                if(city_id!=0){
                    $.ajax({
                        url:'/user/get_area_by_cid',
                        data:{
                            'city_id':city_id
                        },
                        success:function (data) {
                        area_list=eval('('+data.area_list+')')
                        $.each(area_list,function (index,item) {
                            var option='<option value="'+item.pk+'">'+item.fields.aname+'</option>'
                            $('#area_id').append(option)
                            })
                        },
                    })

                }
            })
        }
    </script>
{% endblock topfiles %}
{% block right_content %}
	<div class="right_content clearfix">
		<h3 class="common_title2">收货地址</h3>
		<div class="site_con">
			<dl>
				<dt>当前地址：</dt>
                {% if address %}
				<dd>{{ all_address }}（{{ address.receiver }} 收） {{ address.mobile }}</dd>
                {% else %}
                    <dd>无默认地址</dd>
                {% endif %}
			</dl>
		</div>
		<h3 class="common_title2">编辑地址<span style="color: red;margin-left: 50px">{{ errors }}</span></h3>
		<div class="site_con">
			<form method="post" action="{% url 'user:address' %}">
            {% csrf_token %}
				<div class="form_group">
					<label>收件人：</label>
					<input type="text" name="receiver">
				</div>
                <div class="three">
                    省：<select name="province_id" id="province_id"><option value="0">-------</option></select>
                    市：<select name="city_id" id="city_id"><option value="0">-------</option></select>
                    区：<select name="area_id" id="area_id"><option value="0">-------</option></select>
                </div>
				<div class="form_group form_group2">
					<label>详细地址：</label>
					<textarea class="site_area" name="place"></textarea>
				</div>
				<div class="form_group">
					<label>邮编：</label>
					<input type="text" name="postcode">
				</div>
				<div class="form_group">
					<label>手机：</label>
					<input type="text" name="mobile">
				</div>

				<input type="submit" name="" value="提交" class="info_submit">
			</form>
		</div>
	</div>
{% endblock right_content %}


